resources:
- deployment.yaml
- service.yaml
- ingress.yaml
- pvc.yaml
- configmap.yaml
- secret.yaml
  

images:
- name: ce82202374acr.azurecr.io/cloud-sample
  newTag: latest
- name: cepgstapacr.azurecr.io/cloud-sample
  newTag: "202409241514"
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
