apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloud-82202374-app-pvc
  namespace: cloud-82202374-app
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-standard-lrs
  resources:
    requests:
      storage: 1Gi