FROM cepgbaseacr.azurecr.io/docker.io/openjdk:17-slim

WORKDIR /app

COPY target/template-0.0.1-SNAPSHOT.jar /app/template-0.0.1-SNAPSHOT.jar

RUN chmod +x ./target/template-0.0.1-SNAPSHOT.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "./target/template-0.0.1-SNAPSHOT.jar"]
